### ISSUE TITLE
Be able to move the achievements around (reorder them)

### ISSUE THREAD

**Issue by Fyrexian** [Handyfon/Farchievements#28] opened 2022-01-05 20:47 UTC
It would be nice if I could drag them around, to place them in spots next  to other similar achievements

**Comment by kiloforce** [comment] 2022-10-02 17:34
Vote +1

**Comment by kiloforce** [comment] 2022-10-02 17:47
Looks to be a duplicate of https://github.com/Handyfon/Farchievements/issues/5

**Comment by Handyfon** [comment] 2022-12-06 17:17
Added in 10.1

**Closed by Handyfon** 2022-12-06 17:17 UTC
Labels: enhancement
